const TEAM_BUTTON_DISABLED = "Default disabled";
const TEAM_BUTTON_ACTIVE_TEAM = "Active team";
const TEAM_BUTTON_TIMER_LAUNCHED = "Timer launched";
const TEAM_BUTTON_OTHER_TEAM_INTERACTED = "Other team interacted";
const TEAM_BUTTON_CORRECT_ANSWER = "Correct answer";
const TEAM_BUTTON_WRONG_ANSWER = "Wrong answer";
const TEAM_BUTTON_SUSPENSE = "Suspense";

export {
    TEAM_BUTTON_DISABLED,
    TEAM_BUTTON_ACTIVE_TEAM,
    TEAM_BUTTON_CORRECT_ANSWER,
    TEAM_BUTTON_WRONG_ANSWER,
    TEAM_BUTTON_OTHER_TEAM_INTERACTED,
    TEAM_BUTTON_TIMER_LAUNCHED,
    TEAM_BUTTON_SUSPENSE,
};
