enum TeamStage {
    Unknown,
    PreGame,
    AnnouncingActiveInRound,
    AnnouncingNotActiveInRound,
    AnnouncingRoundTopics,
    SelectingCell,
    CellSelected,
    WaitingForActiveTeamToSelectCell,
    AllowedInteractAsActiveTeam,
    AnsweringAsActiveTeam,
    AnsweredWrongAsActiveTeam,
    TimeIsUpAsActiveTeam,
    AnsweredCorrectlyAsActiveTeam,
    WaitingForActiveTeamToEndItsTurn,
    WaitingForTimerStartToAnswerAsOtherTeam,
    SuspenseAfterOtherTeamInteract,
    AnnouncingNotEnoughAttemptsToInteract,
    ActiveTeamAnsweredCorrectly,
    ActiveTeamAnsweredWrongToRoundEnd,
    AnsweringAsOtherTeam,
    AlreadyInteractedAsOtherTeam,
    AllowedInteractAsOtherTeam,
    OtherTeamAnswering,
    AnsweredCorrectlyAsOtherTeam,
    AnsweredWrongAsOtherTeam,
    OtherTeamsTimerExpired,
    OtherTeamAnsweredCorrectly,
    NoOtherTeamsThatCanAnswer,
    RoundEnded,
    GameEnded,
}

export default TeamStage;
