version: "3.8"
services:
  wombatapp:
    image: wombatgame/app:edge
    container_name: wombat-game-edge
    environment:
      - MetricsOptions__ApplicationName=Wombat-edge
      - InfluxDbOptions__BaseUri=http://influxdb-wombat:8086
    env_file:
      - app.env
    restart: always
    ports:
      - 9696:5000
    volumes:
      - "lite-db:/app/litedb-database"
      - "logs:/app/logs"
    networks:
      - share-network
      - wombat-monitor-services 


volumes:
  lite-db:
  logs:

networks:
  share-network:
    name: wombat-edge-network
  wombat-monitor-services:
    external: true
    name: wombat-monitor-services-network
